#!/bin/bash
COINUSER=chaincoin
PUBLIC_IP=$(curl -s ipecho.net/plain)
coinexplorerurl=https://api.chaincoinexplorer.co.uk/getBlockchainInfo
highestBlock=$(curl -sk $coinexplorerurl | jq .blocks)
sudo -u $COINUSER -H sh -c "echo '{ \"timestamp\": \"`date`\", \"highestBlock\": \"$highestBlock\", \"details\": ['; chaincoin-cli getnetworkinfo; echo ','; chaincoin-cli -getinfo; echo ','; chaincoin-cli mnsync status; echo ','; chaincoin-cli masternode list full $PUBLIC_IP; echo ']}'" | jq .