#!/bin/bash
COINUSER=cropcoin2
PUBLIC_IP=$(curl -s ipecho.net/plain)
coinexplorerurl=https://cropcoin.blockxplorer.info/api/getblockcount
highestBlock=$(curl -sk $coinexplorerurl)
PORT=17730
sudo -u $COINUSER -H sh -c "echo '{ \"timestamp\": \"`date`\", \"highestBlock\": \"$highestBlock\", \"details\": ['; cropcoind masternode status; echo ','; cropcoind getinfo; echo ','; cropcoind masternode list full $PUBLIC_IP:$PORT; echo ']}'"