#!/bin/bash

source tools.sh

function getZenBalancesByAddress() {
    COINUSER=zen
    address=$1
    balance=$(runCommandWithUser $COINUSER "zen-cli z_getbalance $address")
    echo -e "${GREEN}$address,${RED}$balance${NC}"
}

getZenBalancesByAddress $1