#!/usr/bin/perl

if ($time = shift @ARGV) {

        ($sec,$min,$hour,$mday,$mon,$year)=gmtime($time);
        printf "%02d:%02d:%02d %02d/%02d/%04d\n\n",$hour,$min,$sec,$mday,$mon+1,$year+1900
}
else {
        print "timestamp: ";
        while ($time = <STDIN>) {

                ($sec,$min,$hour,$mday,$mon,$year)=gmtime($time);
                printf "%02d:%02d:%02d %02d/%02d/%04d\n\n",$hour,$min,$sec,$mday,$mon+1,$year+1900;
                print "timestamp: "
        }

        die "\nSee ya!\n";
}