#!/bin/bash
source /usr/local/bin/ddhelper.sh

txid=$1
host=$(hostname)
coin="cropcoin"
role="masternode"
username=$(whoami)
tx_base_url=https://cropcoin.blockxplorer.info/tx

title="wallet.transaction"
message="$tx_base_url/$txid"
sentEvent $host $coin "$title" "$message" $role $username
