#!/bin/bash
source /usr/local/bin/ddhelper.sh

txid=$1
host=$(hostname)
coin="arcticcoin"
role="masternode"
username=$(whoami)
tx_base_url=http://explorer.arcticcoin.org/tx

title="wallet.transaction"
message="$tx_base_url/$txid"
sentEvent $host $coin "$title" "$message" $role $username
