#!/bin/bash
COINUSER=zen
PUBLIC_IP=$(curl -s ipecho.net/plain)
sudo -u $COINUSER -H sh -c "echo '{ \"timestamp\": \"`date`\", \"details\": ['; zen-cli getnetworkinfo; echo ','; zen-cli getinfo; echo ','; zen-cli z_gettotalbalance; echo ']}'"