#!/bin/bash

function getBalancesByAddress(){
    address=%1
    balance=$(zen-cli z_getbalance $address)
    echo "$address,$balance"
}

function main(){
    COINUSER=zen
    echo z_addresses
    sudo -u $COINUSER -H sh -c "zen-cli z_listaddresses | jq '.[]' | xargs -I{} getBalancesByAddress {}"
    echo t_addresses
    sudo -u $COINUSER -H sh -c "zen-cli listaddresses | jq '.[]' | xargs -I{} getBalancesByAddress {}"
}

main