#!/bin/bash
#set -xe

source tools.sh

function main() {
    COINUSER=zen
    echo -e "${BLUE}z_addresses${NC}"
    runCommandWithUser $COINUSER "zen-cli z_listaddresses | jq '.[]' | xargs -I{} getZenBalancesByAddress {}"
    
    echo
    echo -e "${CYAN}t_addresses${NC}"
    runCommandWithUser $COINUSER "zen-cli listaddresses | jq '.[]' | xargs -I{} getZenBalancesByAddress {}"
}

main